# -*- coding: utf-8 -*-
"""Extract_Twine_Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mTgButex5ezB4JcH31obnBtZ1recHnb0
"""

from bs4 import BeautifulSoup
soup = BeautifulSoup(open('/content/Catch_Bean_If_You_Can_Proofing.txt'))
list = soup.select(".textOpt")
print(list)